### ISSUE TITLE
Syl separation issue when syl is after neueme

### ISSUE THREAD

**Issue by kemalkongar** [DDMAL/MEI2Volpiano#11]
This is a medium priority issue. TODO after volpiano export works.

When 'syl' is before the neuemes, dictrionary function fails to properly space the components. This can be fixed by changing primary focus from 'syl' to 'syllable' and assingning a dummy key until the next syl is found. 

To fix later.

**Comment by GabbyHalpin** [comment]
This issue has been fixed, the placement of the syllables should not impact the resulting output as it did before.
