### ISSUE TITLE
Add github actions workflow

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#23]
Add a Github Actions workflow for this repository (`.github/workflows/...`)

Using one of the peer-reviewed templates suggested by GH is preferred.

At the bare minimum, we want the following:
- [x] Basic linting with `pylint`, `flake8` or similar
- [x] Run and verify `pytest` tests on commit/PR to `main`
- [x] Run on at least Python 3.8 and 3.9. The more the merrier.

**Comment by GabbyHalpin** [comment]
So the workflow has been created, and it builds python versions 3.6 and up. There may still be some tweaking to do on the file
