### ISSUE TITLE
Short markdown explanation of what a "Western Music Notation" should look like to be valid

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#27]
Common Western Music Notation could be encoded in very diverse ways.

How does a CWMN input `mei` file needs to look to be processed by the `-W` flag?

Even better, add a unit test for CWMN inputs to the test suite.

**Comment by kemalkongar** [comment]
Newest dev version has hybrid testing for Neueme and Western. Both the debugging methods and the respective volpiano conversion methods are tested. All tests pass. 

Added 2 more bulletpoints as to how we expect CWMN MEI files to look like.
