### ISSUE TITLE
argparse is not used

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#3]
`argparse` is a python library to parse argument from the console (i.e., to make a CLI interface for a script).

https://docs.python.org/3/library/argparse.html

In the current code, it is being imported

https://github.com/DDMAL/MEI2Volpiano/blob/58f88fbb2c00d206f53ab5b21a0f11cf3094c60f/mei2volpiano.py#L9

but not used

https://github.com/DDMAL/MEI2Volpiano/blob/58f88fbb2c00d206f53ab5b21a0f11cf3094c60f/mei2volpiano.py#L53

`argparse` is preferred over reading `sys.argv`

**Comment by deepio** [comment]
can even go further if you want to get fancy
[click](https://click.palletsprojects.com/en/7.x/) > [argparse](https://docs.python.org/3/library/argparse.html) > `sys.argv`

**Comment by raviraina** [comment]
argparse implemented in dev branch
