### ISSUE TITLE
Add link to homepage in PyPI page

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#36]
The homepage link should link to this repo.

It seems only an admin can do that, so either @martha-thomae or @deepio, could you add the link?

It'd be helpful to link people to this repo if they find the package on PyPI.

**Comment by deepio** [comment]
it's not on pypi's side that you do that

**Comment by deepio** [comment]
Close the issue on the next push

**Comment by deepio** [comment]
not sure why it's not in the issue history anymore https://github.com/DDMAL/MEI2Volpiano/commit/b8dfc65b51285a5b5e86805e5d225b0e417b0636
