### ISSUE TITLE
Use a dedicated python xml library instead of line-by-line 

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#4]
Given how complex MEI files can get, it is not robust to parse them line by line.

The use of an xml parser is much better for this purpose.

I recommend looking into the official python tool for this: https://docs.python.org/3/library/xml.etree.elementtree.html

Either that or the `defusedxml` alternative. I don't have security concerns for this code (the main motivation for `defusedxml`), given that we plan to use it with in-house xml files only, so I think the official one is a better choice.

**Comment by kemalkongar** [comment]
Given the issues with libmei we'll go with ET for now!

**Comment by napulen** [comment]
Go for it

**Comment by kemalkongar** [comment]
Issue can be closed per the latest push into master.
