### ISSUE TITLE
Idiomatic code

### ISSUE THREAD

**Issue by napulen** [DDMAL/MEI2Volpiano#5]
https://github.com/DDMAL/MEI2Volpiano/blob/58f88fbb2c00d206f53ab5b21a0f11cf3094c60f/mei2volpiano.py#L41

This line is probably going to change based on the use of `xml` libraries. However, it is a good example to present (and request) idiomatic patterns:

```python
if "A" <= char <= "Z":
```

**Comment by raviraina** [comment]
fixed in dev branch, although as you said this section may change in a later commit
