### ISSUE TITLE
Looking into hyphens for words, syllables, neume components

### ISSUE THREAD

**Issue by GabbyHalpin** [DDMAL/MEI2Volpiano#6]
-test for git account also, check for hyphens.

**Comment by GabbyHalpin** [comment]
Normally, the structure would be 3 hyphens for words, 2 for syllables, and 1 between Neumes.
However we will start with 3 for syllables, 1 for Neumes until the issue with the words that was discussed on slack can be resolved.

**Comment by kemalkongar** [comment]
Closed per current MEI standard and OMR output -- words are not tracked so we take syllables as the 'largest' components.
